ondras/rot.js

- manual/pages/hex/indexing.html
As discussed, &minus; entities was replaced by basic minuses to prevent hard to spot errors when copy-pasting offsets to source code.
> replace &minus; with plain `-`, as per #49

- manual/pages/display.html
- rot.js
- src/display/display.js
- src/display/tile.js
This uses globalCompositeOperation to allow foreground/background colours on tile displays. I'm using this to render bitmap fonts. It works with draw & drawtext. To render the image without colours, set both foreground and background to 'transparent'.
> added support for tile colours

- Makefile
- node/node-export.js
- node/node-shim.js
- node/package.node
- node/term-color.js
- node/term.js
- node/xterm-color.js
- package.json
- src/display/display.js
So this is rot.js with support for Node.js. It offers a new build target `node`:
make clean
make node
This will recreate `package.json` and create `lib/rot.js`.
Once the Node version of rot.js is built, package.json specifies everything that npm needs in order to publish. Publishing to npm is just:
npm publish
I have added `ondras` as an owner on the `rot-js` npm module, so you should be able to publish and add/remove owners now. If you want me to publish, just let me know and I'll do so.
After publication, the most simple way to try out rot.js for Node would be:
npm install rot-js
node -e 'var ROT = require("rot-js"); console.log(ROT.isSupported());'
* I did not delete the existing `package.json` file in order to keep the diff short and clear. I do think it should be deleted, or at least …
> First pass at merging Node.js support

- manual/pages/intro.html
Add a link to WebJars from the introduction section.
Unfortunately, there is no direct way to directly link rot.js on the WebJars site so I've decided to simply link their main page. It will be sufficient for guys who use WebJars :)
We've already used this jar-version of rot.js in the [Keter](https://github.com/codingteam/Keter/) project and it works well.
> Add a link to WebJars

- src/map/digger.js
The y-coordinate is now compared with height instead of width. As a micro-optimization, I've also pulled the comparison out of the loop.
> Logic fix in Map.Digger._getDiggingDirection.

- src/map/rogue.js
Changed from brackets to parens so as to prevent !this._options.hasOwnProperty["roomHeight"] from always returning true (!undefined). No other changes made.
Before:
if (!this._options.hasOwnProperty["roomHeight"]) {
this._options["roomHeight"] = this._calculateRoomSize(this._height, this._options["cellHeight"]);
}
After:
if (!this._options.hasOwnProperty("roomHeight")) {
this._options["roomHeight"] = this._calculateRoomSize(this._height, this._options["cellHeight"]);
}
> Fix logic in ROT.Map.Rogue to use parens per #62

- src/map/rogue.js
Per optimization suggestion in #62, I replaced all references to Rogue's internal random number generator with calls to ROT.RNG.getUniformInt. Removed now-defunct ROT.Map.Rogue.prototype._getRandomInt. No other changes made.
Example Before:
var cgx = this._getRandomInt(0, this._options.cellWidth-1);
var cgy = this._getRandomInt(0, this._options.cellHeight-1);
Example After:
var cgx = ROT.RNG.getUniformInt(0, this._options.cellWidth-1);
var cgy = ROT.RNG.getUniformInt(0, this._options.cellHeight-1);
> Replace references to getRandomInt with ROT.RNG.getUniformInt

- manual/pages/tiles.html
In the tiles manual page there was a missing ‘d’ for the word ‘third’.
> Spelling fix

- rot.js
- src/display/display.js
Couldn't figure out how to write a spec for this, but it comes into play when the container canvas is scaled with a percentage value. The change can be seen comparing
original: http://tps12.github.io/rot.js/scale-demo-original.html
to
modified: http://tps12.github.io/rot.js/scale-demo-modified.html
> Make eventToPosition scale to client dimensions

- rot.js
- src/path/astar.js
- tests/spec/path.js
Found that small tweaks to A* can dramatically alter the performance in certain cases (linear visits in size of path down from squared). I wrote a few notes with demo [here](http://humbit.com/pathfinding/test.html). I tried adding the least obtrusive of the changes (tiebreaking when f scores are equal) and attempted to write a test for it.
This is my first pull request for anything so I apologize if I'm missing something obvious.
> Adding tiebreaking to A*

- src/map/rogue.js
Nothing specifically addressed in #62, though it looks like there were additional unused variables that were initialized but never used.
Summary:
Removed unused variables.
Fixed spelling error in "_drawCorridore" method.
Made code style more internally consistent.
> Clean up ROT.Map.Rogue

- src/eventqueue.js
- src/scheduler/scheduler-speed.js
- src/scheduler/scheduler.js
- tests/spec/eventqueue.js
- tests/spec/scheduler.js
Adds an additional optional time argument to Scheduler.Speed.add(), which
defines an initial time to schedule the item. If the item is repeated then
subsequent scheduling will use 1/item.getSpeed() as before.
Also exposes an item's time through a Scheduler.getTimeOf(item) method. In
combination, these two changes allow clients to completely recreate the
state of the speed scheduler at a given point, useful when saving and
restoring a game state.
> Allow Speed scheduler to accept an initial time

- src/display/display.js
When the rendering engine decides that a character is full-width, it skips a space, leaving it untouched, and continues in the next space. This looks _really_ bad when the character is not, in fact, full-width. (I don't know if it looks good when the character _is_ full-width.) This patch just fixes the detection of full-width characters in the Basic Multilingual Plane. (That last `cc > 0xffee` is also wrong, but didn't seem worth fixing.)
There's probably still issues with this line, as this change also squishes Chinese characters together for example... but Chinese characters didn't fit vertically into the cell either in my quick test. Still, additional ranges for CJK ideographs probably need to be added.
> Fix most non-ASCII characters treated as fullwidth

- src/map/cellular.js
This was causing the lower part of the map to always be 100% blocked.
> Fix neighbor check for non-square ROT.Map.Cellular

- src/path/astar.js
A node should only be added to the closed set when it is expanded, not when it is added to the queue. Before then, the algorithm could still find a shorter path to it, even with a monotone heuristic.
This can result in the same node appearing multiple times in the priority queue, so when pulling a node off the queue, check if it is already closed and if so, skip it. This is not a correctness issue; it merely avoids redundant effort.
A simple example of why this is needed in the 6 topology:
When pathing from 4 to 3, note that nodes 1 and 5 have the same heuristic value (h = 3), as do 2 and 6 (h = 2). First 4 is expanded, leaving the algorithm indifferent between 1 and 5 (both have h = 3, g = 1). First, 1 will be visited (because of how neighbors are ordered). This will add 2 with h = 2, g …
> Fix closed set usage in AStar

- package.json
🎉🎉 TypeScript, yay!  🎉🎉
However, the `package.json` doesn't expose the typings, so trying to use them in a project doesn't work. 
This pull request makes a tiny change to `package.json` to tell TypeScript where the types are, so when you import this library into a new project, it Just Works® without `@types/rot-js`.
The `package.json` didn't appear to be in any particular order so it was difficult to guess the best place to put it, so I put it at the bottom.
> Expose TypeScript types for library use

- src/rng.ts
Currently, `getWeightedValue` is typed as `data: any`, but it expects the set to have numeric values. This can result in compile-time validity but runtime errors.
**Before PR**
```typescript
RNG.getWeightedValue({ 'monster': 'error!' }) // causes runtime error but compiles fine
```
**After PR**
```typescript
// compile-time error: Type 'string' is not assignable to type 'number'.
RNG.getWeightedValue({ 'monster': 'error!' }) 
// works
RNG.getWeightedValue({ 'monster': 30, 50: 10 }) 
```
If the index signature looks a little odd, here's why: TypeScript expects index signatures to must be literal `string` or `number`, but doesn't allow you to have a `string | number` union. The type in this PR is a signature overload, so TS knows that if the key is a string or a number, the value must be a …
> Strictly type parameter of getWeightedValue

- tsconfig.json
Currently, `tsconfig.json` is configured to remove comments, which results in all of the `.d.ts` files being undocumented. At first, I thought all of these methods weren't documented, but after looking at the code I realized that there's all this good documentation being stripped out.
**Before PR - what's this do?**
**After PR - documentation!**
> Keep .d.ts doc comments for TypeScript

- src/display/display.ts
- src/display/term.ts
cjk characters are full-width characters but rot.js can't draw them on display layout("term")
old encoded cjk characters have 2 codes and move the cursor 2 spaces. 
```
Ah
아
あ
啊
```
unicode cjk character have 1~3 codes and move the cursor 2 spaces.
```
아
0xC544 (unicode)
0xEC, 0x95, 0x84 (utf-8)
```
we can only choose whole cjk character 
and can't choose separated space on terminal(with cjk encoding).
but rot.js can draw some codes in the unknown separated spaces. i think it makes the cjk bug. 
if we avoid the bug, first space is placed unicode character and second space should be empty (and deleted if there is something already.)
i wanted to used the null or empty character for deleting 
but have choosed the other character ('\t') because null or empty character is already used. 
if you …
> drawText: cjk bug fixed

- manual/pages/fov.html
- manual/pages/map/cellular.html
- manual/pages/map/dungeon.html
- manual/pages/map/maze.html
- manual/pages/stringgenerator.html
- src/map/digger.ts
- src/map/iceymaze.ts
- src/stringgenerator.ts
This fixes a few broken RogueBasin links that I noticed during my 7DRL.
I also tried building the project using `make all` but it ended up with a *lot* of differences that appeared not to affect anything but would probably make this harder to review. The results are [here](https://github.com/katerberg/rot.js/tree/built). I'm happy to have that be the PR instead if that's easier, but I'm likely doing something wrong with my build process, or some backing libraries have updated and now there is not a need for the `_partial` prefixing anymore.
I'm happy to document the build process if that would be useful, but I'm not sure how to get it compiled and working.
> Fixes a few broken links

- src/display/canvas.ts
This can also be applied to e.g. Tile.draw() when clearBefore is true and tileColorize is false
> Fix canvas clear when background is transparent/translucent

- .github/workflows/typos-check.yaml
This pull request is intended to fix #219 . By adding an extra github action containing steps to check `src`, `tests`, `tools`, `addons` and `examples` code, typos can be captured during build stage.
However, due to the action's own design, any typos found would cause the action to exit with errors. I believe this is intended to urge users to fix the typos instantly. Only way to prevent this error is submitting codes without typos.
It can't be done to make current code base go through typos checking without errors, some changes to source code must be made.
> Add github action for typos.
